### ISSUE TITLE
team members

### ISSUE THREAD

**Issue by bienvenuushindi** [Sevenpros/meals#22]
https://github.com/Sevenpros/meals/projects/1

We are 2 members

**Comment by zhadier** [comment]
# Hi @bienvenuushindi  & @Sevenpros   👋 

Good job so far! 🌤️ 
There are some issues that you still need to work on to go to the next project but you are almost there! 🍓 

<img src="https://media4.giphy.com/media/5wWf7GR2nhgamhRnEuA/giphy.gif"/>

## Highlights
✔️ Great job adding all of the required tasks

## Required Changes ♻️

- [x] Kindly ensure that you assign the tasks to each student so they know what they're supposed to work on. One person should get all the tasks for student A and the other for student B. The picture of the assignee will appear in the bottom right of the card once it has been assigned. Also, kindly ensure that the points are equally distributed or not very skewed at the very least when you do assign the tasks. I've added a list of steps below to help you on how to assign tasks

> Step 1: Click on a card

![image](https://user-images.githubusercontent.com/90556221/180772429-ea999231-291a-4cae-80b4-678d35cf7aa9.png)

> Step 2: On the popup that appears on the right, click on assignees and assign a person to the task

![image](https://user-images.githubusercontent.com/90556221/180772611-4418b566-4ddf-47dc-9452-e3023d4e0532.png)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question @zhadier so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by youmari** [comment]
# Project Approved :trophy: :tada: 🟢 

Hi @bienvenuushindi @Sevenpros 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linters error.
:heavy_check_mark: Details PR title and description.
:heavy_check_mark: Good commit messages.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U02FTTCCU2V)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
